#!/usr/bin/perl

use Encode;

(@ARGV == 2) or die "Usage: $0 <input file> <output file>\n";

open my $in,  "<:encoding(cp1251)", $ARGV[0] or die "Can not open input file: $!\n";
open my $out, ">:encoding(utf8)",   $ARGV[1] or die "Can not open output file: $!\n";
while ( <$in> ) { print $out $_ }

#if ( @ARGV != 1 ) {
#  print "$0 - CP1251 to UTF8 file converter\n";
#  print "Usage: $0 <input file>\n";
#  exit 0;
#}
#
#use encoding "cp1251", STDOUT => "utf-8";
#
#$infile = $ARGV[0];
#
#open(INFILE, $infile) or die "Error: Can not open file '$infile': $!\n";
#
#while (<INFILE>) {
#  print
#}

